version: '3.8'
services:
  dataflow:
    build: ./Dataflow
    ports:
      - 8001:8001  # Map container's port 8001 to host's port 8001
    networks:
      - web

  ea_grafty:
    build: ./EA_Grafty
    ports:
      - 8000:8000  # Map container's port 8000 to host's port 8000
    networks:
      - web

  reverse-proxy:
    build: ./reverse_proxy
    ports:
      - 80:80
    networks:
      - web

networks:
  web:
