version: '3.8'

services:
  dataflow:
    image: prueba2-dataflow
    ports:
      - 8000:8000
    networks:
      - web

  ea_grafty:
    image: prueba2-ea_grafty
    ports:
      - 8001:8001
    networks:
      - web

  reverse-proxy:
    build: ./reverse_proxy
    ports:
      - 80:80
    networks:
      - web

networks:
  web: